query PurchaseRequests {
  purchaseRequests {
    uuid
    code
    status
    requestedBy
    requiredDate
    notes
    approvedAt
    purchaseOrderCodes
    insertedAt
    items {
      ...PurchaseRequestItemFields
    }
  }
}
