query SalesOrder($request: SalesOrderRequest!) {
	salesOrder(request: $request) {
		...SalesOrderFields
		customer {
			address
			barangay
			city
			province
			region
			postalCode
		}
		items {
			...SalesOrderItemFields
		}
		deliveryNotes {
			...DeliveryNoteFields
		}
		salesInvoices {
			...SalesInvoiceFields
		}
	}
}