query SalesInvoice($request: SalesInvoiceRequest!) {
  salesInvoice(request: $request) {
    ...SalesInvoiceFields
    items {
      uuid
      itemName
      description
      uomName
      qty
      unitPrice
      discount
      lineTotal
    }
  }
}
