query workOrder($request: IdRequest!) {
  workOrder(request: $request) {
    ...WorkOrderFields
    items {
      ...WorkOrderItemFields
      jobCards {
        ...JobCardFields
      }
    }
    materialRequests {
      ...MaterialRequestFields
    }
  }
}
