fragment ItemFields on Item {
  uuid
  name
  itemType
  standardCost
  stockValue
  sku
  category
  spec
  sellingPrice
  minStockThreshold
  onHandQty
  reservedQty
  availableQty
  defaultStockUomUuid
  defaultStockUomName
  insertedAt
  updatedAt
}
