fragment SalesInvoiceFields on SalesInvoice {
  uuid
  code
  status
  amount
  paidAmount
  balance
  customerUuid
  customerName
  salesOrderUuid
  salesOrderCode
  invoiceDate
  dueDate
  paymentTerms
  customerAddress
  customerTin
  customerReference
  vatMode
  subtotal
  discountAmount
  vatableAmount
  vatAmount
  notes
  insertedAt
  updatedAt
}
