fragment SalesOrderFields on SalesOrder {
  uuid
  code
  status
  billingStatus
  deliveryStatus
  customerName
  requiredDate
  notes
  deliveryRisk
  salesInvoiceCode
  totalAmount
  paidAmount
  remainingAmount
  totalQty
  deliveredQty
  remainingQty
  warehouseName
  insertedAt
  updatedAt
}

