fragment WorkOrderFields on WorkOrder {
  uuid
  code
  title
  startTime
  endTime
  type
  status
  plannedQty
  storedQty
  producedQty
  scrapedQty
  itemUuid
  itemName
  uomName
  supplierName
  supplierUuid
  salesOrderUuid
  salesOrderCode
  dueDate
  assignedStaffUuid
  assignedStaffName
  pieceRate
  machineHours
  laborHours
  stockUomUuid
  insertedAt
  updatedAt
}

